language: ruby
rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - ruby-head
gemfile:
  - test/gemfiles/5.2.gemfile
branches:
  only:
    - master
before_install:
  - gem update --system
  - gem update bundler
before_script:
  - rake db:migrate
script:
  - bundle exec rake test
  - bundle exec rubocop
matrix:
  allow_failures:
    - rvm: ruby-head
