language: ruby
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
gemfile:
  - test/gemfiles/Gemfile.rails.5.2
branches:
  only:
    - master
before_install:
  - gem update --system
  - gem update bundler
before_script:
  - rake db:migrate
script:
  - bundle exec rake test
  - bundle exec rubocop
