language: ruby
before_install:
  - gem install bundler
before_script:
  - rake db:migrate
script:
  - rake test
rvm:
  - 2.2.7
  - 2.3.5
  - 2.4.2
gemfile:
  - test/gemfiles/Gemfile.rails.5.2
branches:
  only:
    - master
